U26-17 Реализовать логику авторизации
Eglatcova/NinjaCats pull request #12
Opened 2023-09-02 10:34 UTC by ValeriiaGrigoreva

https://linear.app/yandex-practicum-game-ninjas/issue/U26-17/realizovat-logiku-avtorizacii

2023-09-02 12:59 UTC, AngryPhilomel commented on packages/client/src/api/AuthApi.ts
Ты повторяешь себя в каждом методе c Fetch. Лучше написать приватный метод который будет делать вызов на основе входных данных (Метод, body, pathname) и там же перехватывать ошибки. В публичных методах будет лишь: return this.request(data, 'signup', 'POST').

2023-09-02 13:12 UTC, AngryPhilomel commented on packages/client/src/pages/Game/Game.tsx
Просто копировать один и тот же код во все файлы страниц плохая идея. Уверен что это можно сделать на уровне react-router-dom. На худой конец вынеси логику в отдельный компонент и помещай в файлы страниц уже его. В будуещем мы заменим это на [HOC/HOOK](https://linear.app/yandex-practicum-game-ninjas/issue/U26-34/avtorizaciya-dolzhna-proveryatsya-cherez-otdelno-napisannyj-hook-ili)

2023-09-02 13:15 UTC, AngryPhilomel commented on packages/client/src/pages/Game/Game.tsx
> +    authAPI.getUser().then(res => {
Зачем ты вызываешь AuthAPI напрямую если у тебя написан AuthController?

2023-09-02 13:21 UTC, AngryPhilomel requested changes
Много повтора кода, все это придется потом удалять. Необходимо вынести то что повторяется в настраиваемые функцию/компонент

2023-09-03 09:46 UTC, ValeriiaGrigoreva commented on packages/client/src/pages/Game/Game.tsx
я поискала про роутер, но что-то для нашего написания роутера вариантов не нашла

я думаю, что лучший вариант для нашего случая это действительно HOC, поэтому не вижу особого смысла сейчас это переписывать и добавлять какие-то компоненты, все равно придется это потом менять, поэтому для этого спринта предлагаю так оставить

2023-09-03 10:18 UTC, AngryPhilomel commented on packages/client/src/api/AuthApi.ts
> +          return false
Запрос возвращает res|false, так не должно быть. Возвращай res даже если он не успешный, в нем содержится информация об ошибке

2023-09-03 10:21 UTC, AngryPhilomel commented on packages/client/src/controllers/AuthController.ts
> +      return res ? true : false
А вот здесь уже можно проверить res.ok и выполнить бизнес нужную логику

2023-09-03 10:22 UTC, AngryPhilomel commented on packages/client/src/pages/Game/Game.tsx
Ладно, оставим для рефакторинга. Действительно странно что это разбито на две таски.

2023-09-03 10:31 UTC, AngryPhilomel requested changes
Методы должны иметь возвращаемые значения единого типа. Возврат или bool или res сбивает с толку

2023-09-03 11:33 UTC, AngryPhilomel approved these changes

2023-09-03 11:49 UTC, merged