Init
Eglatcova/NinjaCats pull request #15
Opened 2023-09-04 16:35 UTC by Alex-Andr-19

Задача: https://linear.app/yandex-practicum-game-ninjas/issue/U26-22/sverstat-ekran-s-nachalom-igry

Сверстать экран с началом игры

2023-09-05 18:07 UTC, ValeriiaGrigoreva requested changes
только поправить использование scss

2023-09-05 18:07 UTC, ValeriiaGrigoreva commented on packages/client/src/pages/GameStart/style.scss
> +    height: 100dvh;
здесь, как в задаче по ошибкам тоже нужно scss модули использовать, как в остальном проекте

2023-09-06 11:50 UTC, Alex-Andr-19 commented on packages/client/src/pages/GameStart/style.scss
> +    height: 100dvh;
Исправил

2023-09-06 14:41 UTC, ValeriiaGrigoreva approved these changes

2023-09-06 14:54 UTC, merged