Feat/u26 21
Eglatcova/NinjaCats pull request #29
Opened 2023-09-05 16:45 UTC by Alex-Andr-19

Задача: https://linear.app/yandex-practicum-game-ninjas/issue/U26-21/sverstat-stranicu-liderborda

Сверстать страницу лидерборда

2023-09-05 18:38 UTC, ValeriiaGrigoreva requested changes
вынести данные из компонента + поправить файлы стилей

2023-09-05 18:38 UTC, ValeriiaGrigoreva commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +    {
я думаю, что правильнее вынести мок из компонента, например, в utils/mocks/leaderboard.ts
а месяца в utils/const/months.ts

2023-09-06 11:37 UTC, Alex-Andr-19 commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +    {
Сделал

2023-09-06 14:46 UTC, ValeriiaGrigoreva approved these changes

2023-09-06 14:56 UTC, merged