Feat/u26 33
Eglatcova/NinjaCats pull request #34
Opened 2023-09-08 21:02 UTC by Eglatcova

2023-09-09 10:06 UTC, AngryPhilomel commented on packages/client/sw.ts
> +  '/game-start',
Может снесем эти урлы? Из роутера тоже, кажется они больше не нужны

2023-09-09 10:07 UTC, AngryPhilomel commented on packages/client/sw.ts
> +const CACHE_NAME = 'game-cache-v3'
V3? Я что-то упустил?)

2023-09-09 10:18 UTC, AngryPhilomel approved these changes

2023-09-09 10:40 UTC, Eglatcova commented on packages/client/sw.ts
> +  '/game-start',
я думаю привести приложение в нормальный вид в вс-понед, и эту часть почистить, просто пока они есть на главной

2023-09-09 14:24 UTC, Olegas requested changes
Добрый день. Есть проблемы. Судя по всему приведенное решение не работает с релизной сборкой приложения. Написал комментарии

2023-09-09 14:24 UTC, Olegas commented on packages/client/src/startSW.ts
> +        .register('/sw.ts')
В релизной версии приложения точно не будет файла sw.ts - браузеры не умею в TypeScript. У этого файла как минимум будет другое расширение (.js)
После того как поменяешь, проверь что все работает потому что скорее всего придется еще донастроить Vite что бы он собрал файлы, не находящиеся в папке src отдельно

2023-09-10 09:17 UTC, Olegas approved these changes
Работа принята

2023-09-12 11:23 UTC, merged