U26-42 Добавить API для лидерборда
Eglatcova/NinjaCats pull request #41
Opened 2023-09-25 12:14 UTC by ValeriiaGrigoreva

https://linear.app/yandex-practicum-game-ninjas/issue/U26-42/dobavit-api-dlya-liderborda

2023-09-26 07:49 UTC, AngryPhilomel commented on packages/client/src/components/Game/Game.tsx
> +    })
Вся эта логика не нужна в компоненте, содержимое не будет изменяться где бы мы его не вызывали, перенеси в метод в контроллер, а на вход метода будет подаваться только `points`

2023-09-26 08:06 UTC, AngryPhilomel commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +        ratingFieldName: 'codeNinjasScore',
В нашем случае это константа, лучше убрать в метод контроллера. А на вход метода подавать `cursor` и `limit` для пагинации

2023-09-26 09:25 UTC, AngryPhilomel commented on packages/client/src/components/Game/Game.tsx
> +        date,
Дата и логин здесь тоже не нужны, убери в контроллер

2023-09-26 09:33 UTC, AngryPhilomel requested changes
Не все убрано в методы. Зачем ты force-push делаешь? Потом сделашь squash если хочешь один коммит в итоге

2023-09-26 10:13 UTC, AngryPhilomel approved these changes

2023-09-26 15:49 UTC, manshind commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +interface ILeaderboardData {
лучше вынести этот интерфейс в контроллер

2023-09-26 15:51 UTC, manshind commented on packages/client/src/controllers/LeaderboardController.ts
> +    this.user = useAppSelector(state => state.user)
использовать хуки вне компонентов нельзя.
в этом случае нужно пробрасывать юзера сюда в качестве аргумента, а уже в компоненте писать useAppSelector(state => state.user)

2023-09-26 15:55 UTC, manshind commented on packages/client/src/api/LeaderboardApi.ts
> +} from '../controllers/LeaderboardController'
тут странная зависимость получается.
контроллер делает импорт из апи, а апи делает импорт из контроллера. Такого не должно быть.

тут можно использовать дженерики в качестве аргументов функции из апи https://www.typescriptlang.org/docs/handbook/2/generics.html

2023-09-27 11:07 UTC, manshind approved these changes
🔥

2023-09-27 12:01 UTC, merged