добавлен ssr
Eglatcova/NinjaCats pull request #44
Opened 2023-10-02 22:31 UTC by Eglatcova

2023-10-03 13:09 UTC, marilisok commented on packages/server/index.ts
> +  if (!isDev) {
На мой взгляд, для читаемости лучше перенести на строчку 40, просто с else)

2023-10-03 13:09 UTC, marilisok commented on packages/server/index.ts
> +  app.use('*', async (req, res, next) => {
здесь тоже тяжеловато читать,  предлагаю разнести по блокам, где if(dev) (блок начинается со стоки 23) и все остальное в else

2023-10-03 13:41 UTC, AngryPhilomel commented on packages/server/index.ts
> +import { createServer as createViteServer } from 'vite'
vite не указан как зависимость сервера

2023-10-03 14:44 UTC, AngryPhilomel commented on packages/server/index.ts
> +  const distPath = path.dirname(require.resolve('client/dist/index.html'))
Вынеси пожалуйста здесь и в других местах `client` в переменную окружения. В докере будет другой путь до этой папки

2023-10-03 19:16 UTC, Eglatcova commented on packages/server/index.ts
> +  app.use('*', async (req, res, next) => {
я думала так сделать, но тогда будет дублироваться код, поэтому оставила такой вариант

2023-10-03 19:19 UTC, Eglatcova commented on packages/server/index.ts
> +  if (!isDev) {
тут у каждого ифа разное логическое содержимое, у первого создается сервер, у второго добавляются файлы, поэтому в разных

2023-10-03 19:19 UTC, Eglatcova commented on packages/server/index.ts
> +  const distPath = path.dirname(require.resolve('client/dist/index.html'))
будет поправлено в 8 спринте

2023-10-03 19:23 UTC, AngryPhilomel approved these changes

2023-10-03 19:24 UTC, marilisok commented on packages/server/index.ts
> +  app.use('*', async (req, res, next) => {
Не совсем поняла
Можно тогда сделать функцию и выносить туда, дублирующийся код

2023-10-03 19:26 UTC, marilisok commented on packages/server/index.ts
> +  if (!isDev) {
Это я понимаю, я к тому, что ты можешь сделать что-то подобное 
if(isDev){
   const variablesPath = path.resolve(srcPath, 'src/style/variables')

    vite = await createViteServer({
      server: { middlewareMode: true },
      root: srcPath,
      appType: 'custom',
      css: {
        preprocessorOptions: {
          scss: {
            additionalData: `@import "${variablesPath}";`,
          },
        },
      },
    })

    app.use(vite.middlewares)
}else{
    app.use('/assets', express.static(path.resolve(distPath, 'assets')))
    app.use('/sw.js', express.static(path.resolve(distPath, 'sw.js')))
}

2023-10-03 20:19 UTC, Eglatcova commented on packages/server/index.ts
> +  if (!isDev) {
я стараюсь вообще избегать else по возможности, статья на тему, но их много разных
https://freek.dev/2212-avoid-using-else

вот, то что ты написала,  я бы может использовала if else если было бы так(логики касаются одного и того же)\
if(создание сервера на деве) else {создание сервера на проде}\
но тут две в моем понимании слабо связанные логики, поэтому мне кажется их не надо объединять

2023-10-03 20:19 UTC, Eglatcova commented on packages/server/index.ts
> +  app.use('*', async (req, res, next) => {
получается, если выносить с 23 до конца, повторится вызов app.use и дублирование объявления переменных в разных блоках

2023-10-03 20:34 UTC, marilisok commented on packages/server/index.ts
> +  if (!isDev) {
Статья касается не посредственно вложенных if и else, с такими кейсами я согласана, здесь же вложенности нет 
С if(создание сервера на деве) else {создание сервера на проде} я согласна
Но хочется тогда видеть их хотя бы друг за другом
А не что-то типо 
if(isDev){
  //code
}
//code
if(!isDev){
  //code
}

2023-10-03 20:44 UTC, marilisok commented on packages/server/index.ts
> +  app.use('*', async (req, res, next) => {
Переменные можно вынести наверх(например со строки 19), тогда дублирования не будет, повторится только app.use зато. избавимся от кучи if

2023-10-03 20:53 UTC, Eglatcova commented on packages/server/index.ts
> +  app.use('*', async (req, res, next) => {
переменные рядом с блоками if, тк они относятся к этим блокам if, это все должно быть в одном поле зрения, чтобы не крутить наверх и не искать там

2023-10-03 21:04 UTC, Eglatcova commented on packages/server/index.ts
> +  if (!isDev) {
я избегаю if else, мне он кажется менее читаемым
в статье запись с двумя ифами приводится как пример, поэтому скинула
код который между ифами опустила вниз, тут согласна

2023-10-03 21:11 UTC, marilisok commented on packages/server/index.ts
> +  app.use('*', async (req, res, next) => {
Вообще я не права тебе не придется никуда выносить, просто сразу напишешь, что-то типо 
const templateFromFile = fs.readFileSync(path.resolve(srcPath, 'index.html'), 'utf-8')
const template = await vite.transformIndexHtml(url, template)

Тоже самое с переменной render

Это вынести в функцию
      const appHtml = await render(url)

      const html = template.replace(`<!--ssr-outlet-->`, appHtml)

      res.status(200).set({ 'Content-Type': 'text/html' }).end(html)**

2023-10-03 21:15 UTC, marilisok commented on packages/server/index.ts
> +  if (!isDev) {
Тем неменее код на строке 72 там же else
Просто получается где-то используешь, где-то нет
Просто статью, хорошая статья, спасибо, просто как мне кажется, мы говорим про другой кейс)

2023-10-03 21:23 UTC, Eglatcova commented on packages/server/index.ts
> +  if (!isDev) {
избегаю, но не исключаю, выше написала, что если два логических блока к одному. и тому же относятся, считаю что нормально использовать
в статье два ифа как пример линейного читаемого кода, у меня та же ситуация

2023-10-03 21:25 UTC, Eglatcova commented on packages/server/index.ts
> +  app.use('*', async (req, res, next) => {
app.use все равно будет дублироваться
текущий вариант считаю нормальным и понятным

2023-10-03 21:28 UTC, Eglatcova commented on packages/server/index.ts
> +  app.use('*', async (req, res, next) => {
короче, так до бесконечности можно, по-моему это какой то спор о вкусовщине уже, оставлю пока как есть

2023-10-03 21:41 UTC, marilisok commented on packages/server/index.ts
> +  app.use('*', async (req, res, next) => {
Я написала этот комментарий, потому что для меня код был запутанным:)

2023-10-03 21:43 UTC, marilisok commented on packages/server/index.ts
> +  if (!isDev) {
Ситуация абсолютно, аналогичная той, где ты используешь else
Выше писала, что ты инициализируешь app.use, тут как 2 логических блока относятся к одному и тому же

2023-10-03 21:47 UTC, marilisok commented on packages/server/index.ts
> +  if (!isDev) {
Плюс говоря уже про оптимизацию, лишний раз условие проверяется

2023-10-04 19:05 UTC, Olegas commented on packages/client/src/App.tsx
> +          {router && <RouterProvider router={router} />}
А как это сейчас работает? Если нет роутера то кто нарисует компонент, соответствующий адресу страницы?

2023-10-04 19:05 UTC, Olegas commented on packages/client/src/main.tsx
> +if (window !== undefined) {
Как может быть что у нас нет window но есть document?

2023-10-04 19:06 UTC, Olegas requested changes
Добрый день. Есть пара вопросов по коду. Не понимаю, как это сейчас работает.

2023-10-04 21:25 UTC, Eglatcova commented on packages/client/src/App.tsx
> +          {router && <RouterProvider router={router} />}
допушила рефакторинг,  что это не просто router, а clientRouter 
он создается только, если мы находимся на клиенте, если на сервере, используется ssr.tsx, где есть StaticRouter

2023-10-04 21:25 UTC, Eglatcova commented on packages/client/src/main.tsx
> +if (window !== undefined) {
этот роутер создается только для клиента

2023-10-04 21:27 UTC, Eglatcova commented on packages/client/src/main.tsx
> +if (window !== undefined) {
на всякий случай перебилдила все, проверила на клиенте и сервере, роутер везде работает

2023-10-05 04:40 UTC, Olegas commented on packages/client/src/main.tsx
> +if (window !== undefined) {
У вас не должно быть тут такой вилки. Ее нужно убрать. Если у вас SSR то в main должен быть только hydrateRoot

2023-10-05 04:43 UTC, Olegas commented on packages/client/src/App.tsx
> +          {router && <RouterProvider router={router} />}
Так не надо делать. У вас получается структура компонентов разная на сервере и на клиенте. Скорее всего будут ошибки гидрации в консоли. Совершенно верно, что роутер должен быть свой для каждого приложения. Но его надо реализовать на одном и том же уровне дерева компонентов. Я бы его вынес на самый верхний уровень, как у вас сделано в ssr, убрал его из APP и вставляли бы вместо этого в main. В этом случае дерево компонентов было бы одинаковым - Router -> App при любом построении.

2023-10-05 07:57 UTC, Eglatcova commented on packages/client/src/main.tsx
> +if (window !== undefined) {
убрала

2023-10-05 07:57 UTC, Eglatcova commented on packages/client/src/App.tsx
> +          {router && <RouterProvider router={router} />}
переделала на BrowserRouter, перенесла его в main

2023-10-05 15:09 UTC, Olegas approved these changes
Работа принята

2023-10-05 21:41 UTC, merged