Feat/u26 46
Eglatcova/NinjaCats pull request #47
Opened 2023-10-10 22:36 UTC by Eglatcova

2023-10-11 16:10 UTC, AngryPhilomel commented on packages/server/package.json
> +    "cookie-parser": "^1.4.6",
перенеси cookie-parser в dependencies, он ведь нужен на проде

2023-10-11 16:14 UTC, AngryPhilomel commented on packages/server/package.json
> +    "pg": "^8.11.3",
pg дважды в зависимостях

2023-10-11 16:15 UTC, AngryPhilomel commented on packages/server/db.ts
> +  port: 5432,
host: POSTGRES_HOST,
port: Number(POSTGRES_PORT)

2023-10-11 16:55 UTC, AngryPhilomel requested changes
В комментах

2023-10-11 16:55 UTC, AngryPhilomel commented on packages/server/models/forum/message.ts
А как связаны сообщение с топиком? Не вижу внешнего ключа?

2023-10-11 16:55 UTC, AngryPhilomel commented on packages/server/models/forum/message.ts
А User модели не будет? Форум анонимный?

2023-10-11 16:55 UTC, AngryPhilomel commented on packages/server/models/forum/topic.ts
> +  lastMessage?: string
В модели нет этого поля

2023-10-11 17:47 UTC, AngryPhilomel commented on packages/server/package.json
> +    "cookie-parser": "^1.4.6",
"http-proxy-middleware": "^2.0.6",
    "express-validator": "^7.0.1",
    "sequelize": "^6.33.0",
    "sequelize-typescript": "^2.1.5",
    "cross-fetch": "^4.0.0",
тоже в продакшн зависимости

2023-10-11 17:51 UTC, AngryPhilomel commented on packages/server/models/forum/message.ts
связь есть, извиняюсь

2023-10-11 19:47 UTC, Eglatcova commented on packages/server/db.ts
> +const client = new Client({
1  уже было изначально, пока не стала трогать, зачем нужна не знаю

2023-10-11 19:47 UTC, Eglatcova commented on packages/server/db.ts
> +    await sequelize.authenticate()
поправила

2023-10-11 19:47 UTC, Eglatcova commented on packages/server/package.json
> +    "cookie-parser": "^1.4.6",
поправила

2023-10-11 19:47 UTC, Eglatcova commented on packages/server/package.json
> +    "pg": "^8.11.3",
поправила

2023-10-11 19:48 UTC, Eglatcova commented on packages/server/db.ts
> +  port: 5432,
заменила

2023-10-11 19:48 UTC, Eglatcova commented on packages/server/models/forum/message.ts
модели User нет, при отправке сообщения нужно будет добавлять имя пользователя

2023-10-11 19:49 UTC, Eglatcova commented on packages/server/models/forum/topic.ts
> +  lastMessage?: string
убрала

2023-10-11 19:56 UTC, AngryPhilomel commented on packages/server/db.ts
> +const client = new Client({
Не нужна, ты можешь удалить client. Зачем 2 подключения? Просто в шаблоне было.

2023-10-11 20:14 UTC, AngryPhilomel commented on packages/server/db.ts
>    return null
ненужный return

2023-10-13 10:54 UTC, DazzlingFame approved these changes
Привет, отличная работа!
Критичных замечаний нет, отметил тебе пару мест, в которых можно улучшить код.

2023-10-13 10:54 UTC, DazzlingFame commented on packages/server/api/forum/topic.ts
> +      .catch(() => res.status(500).json({ reason: 'Error' }))
_Не обязательно к исправлению_

Тут можно улучшить эту часть и написать в `reason` не просто заглушку `Error`, а что-то более человекочитаемое и наводящее на источник проблемы

2023-10-13 10:54 UTC, DazzlingFame commented on packages/server/api/forum/topic.ts
> +      .catch(() => res.status(500).json({ reason: 'Error' }))
Аналогично к другим запросам

2023-10-13 10:54 UTC, DazzlingFame commented on packages/server/db.ts
>    return null
_Не обязательно к исправлению_

Да, `return null` тут и правда ничего не делает. Хорошо бы убрать

2023-10-13 13:16 UTC, merged