U26-20 Сверстать страницу регистрации
Eglatcova/NinjaCats pull request #6
Opened 2023-08-23 08:12 UTC by ValeriiaGrigoreva

Регистрация с формой, имена полей: first_name, second_name, login, email, password, phone.

2023-08-27 18:22 UTC, AngryPhilomel commented on packages/client/src/pages/Registration/Registration.tsx
> +      <Input
Это ведь форма? Ее нужно обернуть в тег <form>, иначе как мы будет ее отправлять?

2023-08-27 18:24 UTC, AngryPhilomel commented on packages/client/src/pages/Registration/Registration.tsx
> +      <Link to="/game">
Кнопка должна выполнять регистрацию, а не быть ссылкой на игру. Пусть на первом этапе будет console.log() с данными формы

2023-08-27 18:28 UTC, AngryPhilomel requested changes
Форма не является формой, и не выполняет функции формы

2023-08-28 09:33 UTC, ValeriiaGrigoreva commented on packages/client/src/pages/Registration/Registration.tsx
> +      <Link to="/game">
я там дальше задачу по валидации буду заливать и там это поправлено, поэтому не буду сейчас в эту задачу лишние изменения добавлять

2023-08-28 09:37 UTC, AngryPhilomel approved these changes

2023-08-28 09:39 UTC, merged