Feat/u26 18
Eglatcova/NinjaCats pull request #8
Opened 2023-08-27 14:58 UTC by Eglatcova

задача https://linear.app/yandex-practicum-game-ninjas/issue/U26-18/vyorstka-stranicy-foruma

создание темы топика в отдельную страницу не выносила, добавила на страницу с темами

2023-08-27 17:31 UTC, AngryPhilomel commented on packages/client/src/pages/Forum/Forum.tsx
Здесь слишком много логики для страницы, renderCreationBlockContent и topics нужно вынести в отдельные компоненты.
Названия onCreationButtonClick и closeOnChangeBlock не информативные, они сообщают не что они делают, а когда они должны вызваться

2023-08-27 17:42 UTC, AngryPhilomel commented on packages/client/src/pages/ForumMessages/ForumMessages.tsx
Опечатка "Messaege" в нескольких местах.
Компонент страницы снова переусложнен, renderMessages можно вынести в собственный компонент.

2023-08-27 17:43 UTC, AngryPhilomel commented on packages/client/src/pages/ForumMessages/ForumMessages.tsx
> +    return messagesItems
Бесполезный return, можно возвращать сразу результат map

2023-08-27 17:46 UTC, AngryPhilomel requested changes
Компоненты страниц очень сложные, В них не следует хранить там много логики. Необходимо разбить на более мелки компоненты. Так будет проще потом их изменять, тестировать, писать стили.

2023-08-27 19:00 UTC, AngryPhilomel commented on packages/client/src/pages/Forum/components/CreationBlock/CreationBlock.tsx
> +  isCretionOn: boolean
Опечаточка

2023-08-27 19:04 UTC, AngryPhilomel commented on packages/client/src/pages/Forum/components/CreationBlock/CreationBlock.tsx
> +  isCretionOn: boolean
Опечаточка

2023-08-27 19:15 UTC, AngryPhilomel commented on packages/client/src/pages/ForumMessages/ForumMessages.tsx
> +  const [currentMeaasges, setCurrentMessages] = useState(messages)
Meaasges

2023-08-27 19:16 UTC, AngryPhilomel approved these changes

2023-08-28 07:21 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/components/CreationBlock/CreationBlock.tsx
> +  return <div className={classes.creationBlock}>{renderContent()}</div>
Рекомендация: нет смысла разносить на сабфункции рендеринга такие вещи
Проще будет поступить следующим образом:
```
return (
  isCreationOn 
    ? JSX
    : JSX
)
```

2023-08-28 07:23 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/components/Topics/Topics.tsx
> +  const topicItems = Object.values(topics).map(topic => {
Предлагаю воспользоваться мемоизацией в подобном случае с помощью useMemo

Выносить в отдельные переменные не очень хорошо, лучше вынести в отдельный компонент TopicItem вёрстку и т.д, мапим и отображаем в топике

2023-08-28 07:24 UTC, IvanPeleshok commented on packages/client/src/pages/ForumMessages/Components/Messages/Messages.tsx
> +    return (
Аналогично, MessageItem

2023-08-28 07:29 UTC, IvanPeleshok requested changes
Проделана огромная работа, вы молодец :)

Из недостатков данной работы могу отметить то, что в компонентах присутствуют сабфункции с возвратом JSX разметки
В таких случаях лучше будет декомпозировать вёрстку в отдельные компоненты, так будет возможность написать модульные тесты более простым образом, масштабироваться и т.д

Просьба доработать и посмотреть замечания не только в том месте, где есть замечание, но и посмотреть аналогичные кейсы

2023-08-28 17:51 UTC, Eglatcova commented on packages/client/src/pages/Forum/components/CreationBlock/CreationBlock.tsx
> +  return <div className={classes.creationBlock}>{renderContent()}</div>
хотела так сделать, но тогда creationBlock будет дублироваться

2023-08-28 17:51 UTC, Eglatcova commented on packages/client/src/pages/Forum/components/Topics/Topics.tsx
> +  const topicItems = Object.values(topics).map(topic => {
поправила

2023-08-28 17:51 UTC, Eglatcova commented on packages/client/src/pages/ForumMessages/Components/Messages/Messages.tsx
> +    return (
поправила

2023-08-28 19:08 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/Forum.tsx
> +  const topicItems = useMemo(
Я бы предложил подобные вещи выносить в основную вложенность вёрстки
Сабфункции с возвратом JSX можно вынести, как отдельный компонент декомпозировав логику

Прекрасно, что использован хук useMemo, респект :)

2023-08-28 19:11 UTC, IvanPeleshok commented on packages/client/src/pages/ForumMessages/ForumMessages.tsx
> +  const renderMessages = () => {
Аналогично

Предлагаю вынести в отдельный компонент
Далее, когда компонент будет расти - ему, возможно, нужен будет доступ к стору, истории и т.д
Слишком много логики для одного модуля

Разнеси, пожалуйста, здесь и в других местах в рамках PR на компоненты такие вещи

2023-08-28 19:12 UTC, IvanPeleshok requested changes
Всё прекрасно, кроме одного момента, который необходимо поправить во всех похожих местах :)

2023-08-28 21:39 UTC, Eglatcova commented on packages/client/src/pages/Forum/Forum.tsx
> +  const topicItems = useMemo(
извините, я не понимаю как именно поправить, мне нужен подробный пример кода

2023-08-28 21:40 UTC, Eglatcova commented on packages/client/src/pages/ForumMessages/ForumMessages.tsx
> +  const renderMessages = () => {
вроде поправила

2023-08-29 05:39 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/Forum.tsx
> +  const topicItems = useMemo(
Речь идёт о том, чтобы была следующая структура:

const topicItems выносим, как компонент, т.е создаём компонент TopicItems (Topics)
Внутри него, по аналогии с сообщениями, используем Topic, как это сейчас и реализовано в маппинге

Пытаюсь донести следующее: нет никакой необходимости в том, чтобы объявить функцию или переменную в компоненте, которая вернёт JSX
Мы просто берём и используем JSX внутри основного return компоненты
В подобном случае, у нас получается плоская структура и всё декомпозировано
Пример:

```
const Forum: FC = () => {
  ...
  
  return (
    <Wrapper>
      <div className={classes.creationBlock}>
        <CreationBlockContent
          value={newTopicLabel}
          isCreationOn={isTopicCretionOn}
          onChange={onChangeTopicValue}
          onConfirm={createNewTopic}
          onClose={offTopicCreation}
          onCreation={onTopicCreation}
        />
      </div>
      <div className={classes.topics}>
        <div className={classes.topicsHeader}>
          <div className={classes.topicsHeaderColumn}>Название темы</div>
          <div className={classes.topicsHeaderColumn}>Кол-во сообщений</div>
          <div className={classes.topicsHeaderColumn}>Последнее сообщение</div>
        </div>
        **<Topics />**
      </div>
    </Wrapper>
  )
}
```

2023-08-29 05:41 UTC, IvanPeleshok approved these changes
Замечательная работа, критических замечаний нет
Хорошо потрудились 👍

2023-08-29 05:41 UTC, IvanPeleshok commented on packages/client/src/pages/ForumMessages/ForumMessages.tsx
> +  const renderMessages = () => {
Да, про это и шла речь)

2023-08-29 05:42 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/Forum.tsx
> +  const topicItems = useMemo(
Если коротко, то аналогично тому, как была декомпозирована логика Messages

2023-09-05 19:47 UTC, merged