U26-19 Добавьте валидацию на все формы
Eglatcova/NinjaCats pull request #9
Opened 2023-08-28 19:31 UTC by ValeriiaGrigoreva

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-08-28 20:35 UTC, Eglatcova commented on packages/client/src/components/Input/Input.tsx
> +import { useState } from 'react'
2 импорта из react нужно объединить в один

2023-08-28 20:35 UTC, Eglatcova commented on packages/client/src/components/Input/Input.tsx
> +
можно сократить
      
if (validationName) {
        const validationResult = validate(validationName, e.target.value)
        setError(validationResult ? '' : validationResult)
      }

2023-08-28 20:35 UTC, Eglatcova commented on packages/client/src/components/Input/Input.tsx
> +    function onBlur(e: React.FocusEvent) {
React.FocusEvent\<HTMLInputElement\>, тогда по идее ниже не нужно будет типизировать e.target

2023-08-28 20:35 UTC, Eglatcova commented on packages/client/src/pages/Login/Login.tsx
> +        }
можно убрать вложенный if
   
if (fieldValidationName && !validate(fieldValidationName, fieldValue)) {
  validationResult = false
}

2023-08-28 20:35 UTC, Eglatcova commented on packages/client/src/pages/Registration/Registration.tsx
> +  function onSubmit(e: React.FormEvent) {
тут тоже можно в дженерик HTMLFormElement добавить

2023-08-28 20:35 UTC, Eglatcova commented on packages/client/src/pages/Registration/Registration.tsx
> +        }
тоже можно убрать вложенный if

2023-08-28 20:35 UTC, Eglatcova commented on packages/client/src/components/Input/Input.tsx
> +          validation-name={validationName}
validationName

2023-08-29 05:17 UTC, ValeriiaGrigoreva commented on packages/client/src/pages/Login/Login.tsx
> +        }
там дальше еще логика для авторизации будет, поэтому тут лучше так оставить

2023-08-29 05:20 UTC, ValeriiaGrigoreva commented on packages/client/src/pages/Registration/Registration.tsx
> +  function onSubmit(e: React.FormEvent) {
все равно хочет типизацию таргета, поэтому оставила так

2023-08-29 05:21 UTC, ValeriiaGrigoreva commented on packages/client/src/pages/Registration/Registration.tsx
> +        }
тоже будет логика регистрации

2023-08-29 05:24 UTC, ValeriiaGrigoreva commented on packages/client/src/components/Input/Input.tsx
> +          validation-name={validationName}
пользовательские атрибуты в camelCase не проходят

2023-08-29 09:22 UTC, Eglatcova commented on packages/client/src/components/Input/Input.tsx
> +          validation-name={validationName}
ок, тут нужно дать ему один смысл, либо пользовательский атрибут, либо пропс
если как пользовательский атрибут, то нужен префикс data-*

в функцию validate передавать инпут, и брать из него value и validation-name
типа такого, тогда пропс вообще не нужен

export function validate(field: HTMLInputElement) {
// почти то же ты уже делаешь на странце регистрации
 const validationName = field.getAttribute('data-validation-name')
 const {value} = field

  const validationResult =
    validationRules[validationName as keyof typeof validationRules].test(value)
  return validationResult
    ? true
    : errorMessages[validationName as keyof typeof errorMessages]
}

дата атрибуты
https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

2023-08-29 09:24 UTC, Eglatcova commented on packages/client/src/pages/Registration/Registration.tsx
> +        }
тут и во втором месте можно чуть сократить
 if (!validate( аргумент))

2023-08-29 09:42 UTC, ValeriiaGrigoreva commented on packages/client/src/pages/Registration/Registration.tsx
> +        }
так не получится, потому что валидация возвращает true, если все хорошо и текст ошибки, если нет, поэтому проверка именно на true

2023-08-29 10:47 UTC, ValeriiaGrigoreva commented on packages/client/src/components/Input/Input.tsx
> +          validation-name={validationName}
переделала, но пропс все равно нужен, чтобы значение атрибута устанавливать

2023-08-29 17:30 UTC, IvanPeleshok commented on packages/client/src/pages/Login/Login.tsx
> +    const formElements: Element[] = Array.from(
Добрый день :)

Вижу, что написан велосипед и в каждом компоненте требующем валидации он повторяется

Давайте перепишем данную реализацию на [Fokmik](https://www.youtube.com/watch?v=7Ophfq0lEAY&ab_channel=OnelightWebDev) + [Yup](https://github.com/jquense/yup)
Таким образом, код станет проще, гибче и масштабируемым
Примеры: 
https://www.youtube.com/watch?v=7Ophfq0lEAY&ab_channel=OnelightWebDev

2023-08-29 17:34 UTC, IvanPeleshok requested changes
Проделана огромная работа
Замечательно, что знаете как своими руками написать валидацию, но хотелось бы избежать бойлерплейта (повторяющегося, повторного кода), поэтому предлагаю воспользоваться готовым решением

2023-08-29 18:48 UTC, ValeriiaGrigoreva commented on packages/client/src/pages/Login/Login.tsx
> +    const formElements: Element[] = Array.from(
Здравствуйте! А не проще вынести логику просто из onSubmit в отдельную функцию в файлике validation.ts и ее использовать? Тогда повторяющегося кода в каждой странице не будет

2023-08-30 16:02 UTC, IvanPeleshok commented on packages/client/src/pages/Login/Login.tsx
> +    const formElements: Element[] = Array.from(
Всё равно это велосипед, который можно избежать
Если нет никакого желания внедрить новые либы и расширить свой багаж знаний, то можно вынести (поставлю апрув, если всё будет ок)

2023-08-30 16:04 UTC, IvanPeleshok commented on packages/client/src/pages/Login/Login.tsx
> +    const formElements: Element[] = Array.from(
Но мы говорим не только о самой валидации, но также и про обработку ошибок и т.п (много плюшек полезных)

2023-08-30 16:05 UTC, IvanPeleshok commented on packages/client/src/pages/Login/Login.tsx
> +    const formElements: Element[] = Array.from(
Очень рекомендую писать близкий к продакшену код :)

2023-08-31 09:39 UTC, IvanPeleshok approved these changes
Проделана огромная работа!
Вы большая молодец!
Поздравляю, работа принята!

2023-09-01 08:10 UTC, merged